FROM mcr.microsoft.comdotnetcoresdk2.2 AS build-env
WORKDIR app

# Copy csproj and restore as distinct layers
COPY .csproj .
RUN dotnet restore

# Copy everything else and build
COPY . .
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.comdotnetcoreaspnet2.2
WORKDIR app
COPY --from=build-env appout .
ENTRYPOINT [dotnet, StudentCourses.WebAPI.dll]